name: flutter_contacts_crm
description: CRM Danh bแบก Flutter + Isar
publish_to: "none"
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  flutter_riverpod: ^2.5.1
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  url_launcher: ^6.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  isar_generator: ^3.1.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true